### ISSUE TITLE
Cannot install this module the way it's written in the doc 

### ISSUE THREAD

**Issue by Cryde** [thephpleague/uri-query-parser#2]
Hello

When I do  ```composer require league/uri-query-parser``` as mentionned in the doc [http://uri.thephpleague.com/query-parser/1.0/](http://uri.thephpleague.com/query-parser/1.0/)
I got this error : 

```
 [InvalidArgumentException]                                                                            
  Could not find a version of package league/uri-query-parser matching your minimum-stability (stable)  
  . Require it with an explicit version constraint allowing its desired stability.   
```

**Comment by nyamsprod** [comment]
@Cryde Indeed the documentation is a little bit ahead of time because the 1.0.0 version is in review period. I'll release it this january when I have time as all issue have been resolve for the release.

**Comment by nyamsprod** [comment]
Also to be totally honest I'm no quite sure about the PHP versions to support. I'm thinking of dropping PHP7.1 support before release ? thoughts :thinking:

**Comment by nyamsprod** [comment]
version 1.0.0 is out and requires PHP7.2+
