### ISSUE TITLE
Possible bug with urldecoding twice 

### ISSUE THREAD

**Issue by arnaspet** [thephpleague/uri-query-parser#3]
### Bug Report

| Information | Description |
|--------------|---------|
| Version | 1.0.0  |
| PHP version | 7.2.0 |
| OS Platform |  osx or debian |

#### Summary

I see that when i use `::extract()` method it decodes my query value twice, which results in unexpected results sometime ( in this case % value is used inside query value ).

#### Standalone code, or other way to reproduce the problem

`QueryString::extract('q=%25car')`

#### Expected result

`['q' => '%car']`

#### Actual result

`['q' => '�r']`

**Comment by nyamsprod** [comment]
@arnaspet I've created a PR to resolve the issue could you try the branch and validate the changes if possible :+1: thanks in advance

**Comment by nyamsprod** [comment]
this bug is fixed and will be release on the next patch/minor release
