### ISSUE TITLE
QueryString::build should not return null

### ISSUE THREAD

**Issue by teohhanhui** [thephpleague/uri-query-parser#5]
#### Summary

Returning `null` is unexpected. It should return an empty string instead, as an empty string is a valid query string.

**Comment by nyamsprod** [comment]
Yes it should return `null` which is the result if for instance the submitted pair is the empty array. Otherwise you will have an issue making the difference between the empty string and the absence of the said query string.

this query string generated by `http://example.com?` is different from the one generated by `http://example.com` in the latter case ... the query string is `null`

**Comment by teohhanhui** [comment]
I see RFC3986 allows zero characters for the `query` component. However, isn't a zero-length query string semantically the same as not providing the query component? Does it really make sense otherwise?

**Comment by teohhanhui** [comment]
I think this discussion would be helpful for us: https://github.com/psf/requests/issues/2912#issuecomment-161267737

**Comment by teohhanhui** [comment]
So, you're right.

>    Normalization should not remove delimiters when their associated
>    component is empty unless licensed to do so by the scheme
>    specification.  For example, the URI "http://example.com/?" cannot be
>    assumed to be equivalent to any of the examples above.  Likewise, the
>    presence or absence of delimiters within a userinfo subcomponent is
>    usually significant to its interpretation.  The fragment component is
>    not subject to any scheme-based normalization; thus, two URIs that
>    differ only by the suffix "#" are considered different regardless of
>    the scheme.

https://tools.ietf.org/html/rfc3986#section-6.2.3

**Comment by nyamsprod** [comment]
FWIW that's one reason I moved away of the PSR UriInterface because it normalized to empty string and in doing so makes everything a bit more complicated if you are using an Uri for anything else but PSR-7
